package com.myolwinoo.universalyoga.admin.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF246A4B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFABF2CA)
val onPrimaryContainerLight = Color(0xFF002113)
val secondaryLight = Color(0xFF4D6356)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E8D7)
val onSecondaryContainerLight = Color(0xFF0B1F15)
val tertiaryLight = Color(0xFF3C6472)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC0E9FA)
val onTertiaryContainerLight = Color(0xFF001F28)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FBF4)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF5FBF4)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFDCE5DC)
val onSurfaceVariantLight = Color(0xFF404943)
val outlineLight = Color(0xFF707972)
val outlineVariantLight = Color(0xFFC0C9C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322E)
val inverseOnSurfaceLight = Color(0xFFEDF2EC)
val inversePrimaryLight = Color(0xFF8FD5AF)
val surfaceDimLight = Color(0xFFD6DBD5)
val surfaceBrightLight = Color(0xFFF5FBF4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EF)
val surfaceContainerLight = Color(0xFFEAEFE9)
val surfaceContainerHighLight = Color(0xFFE4EAE3)
val surfaceContainerHighestLight = Color(0xFFDEE4DE)

val primaryDark = Color(0xFF8FD5AF)
val onPrimaryDark = Color(0xFF003823)
val primaryContainerDark = Color(0xFF005235)
val onPrimaryContainerDark = Color(0xFFABF2CA)
val secondaryDark = Color(0xFFB4CCBC)
val onSecondaryDark = Color(0xFF203529)
val secondaryContainerDark = Color(0xFF364B3F)
val onSecondaryContainerDark = Color(0xFFD0E8D7)
val tertiaryDark = Color(0xFFA4CDDD)
val onTertiaryDark = Color(0xFF053542)
val tertiaryContainerDark = Color(0xFF234C5A)
val onTertiaryContainerDark = Color(0xFFC0E9FA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDEE4DE)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDEE4DE)
val surfaceVariantDark = Color(0xFF404943)
val onSurfaceVariantDark = Color(0xFFC0C9C1)
val outlineDark = Color(0xFF8A938C)
val outlineVariantDark = Color(0xFF404943)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DE)
val inverseOnSurfaceDark = Color(0xFF2C322E)
val inversePrimaryDark = Color(0xFF246A4B)
val surfaceDimDark = Color(0xFF0F1511)
val surfaceBrightDark = Color(0xFF353B36)
val surfaceContainerLowestDark = Color(0xFF0A0F0C)
val surfaceContainerLowDark = Color(0xFF171D19)
val surfaceContainerDark = Color(0xFF1B211D)
val surfaceContainerHighDark = Color(0xFF262B27)
val surfaceContainerHighestDark = Color(0xFF303632)







